version: '3.8'
services:
  backend:
    build: ./backend/dodecaphony-backend
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend/dodecaphony-ui
    ports:
      - "3000:80"
    depends_on:
      - backend