name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger this workflow when changes are pushed to the 'main' branch

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username (GitHub Secret)
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub password/Access Token (GitHub Secret)
  IMAGE_NAME: oberhamberger/dodecaphony-gen # Replace with your Docker Hub username and image name

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Action to log in to Docker Hub
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5 # Action to generate Docker tags and labels
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short,prefix=sha- # Tags with short commit SHA (e.g., sha-abcdef1)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/dodecaphony-backend
          file: ./backend/dodecaphony-backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}-backend:latest
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/dodecaphony-ui
          file: ./frontend/dodecaphony-ui/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}-frontend:latest
